name: authentication
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

#-------- PACKAGES ----------#
dependencies:
  flutter:
    sdk: flutter

  #UTILITY PACKAGES
  http: ^1.2.2
  intl: ^0.20.1
  logger: ^2.5.0
  url_launcher: ^6.3.1
  flutter_native_splash: ^2.4.3
  smooth_page_indicator: ^1.2.0+3

  #ICONS
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8

  #STATE MANAGEMENT
  get: ^4.6.5
  get_storage: ^2.1.1

  #Firebase
  firebase_core: ^3.10.1



  #PRODUCT SPECIFIC


  #Curved Navigation Bar#

  curved_navigation_bar: ^1.0.6

  #Caurosel Slider
  carousel_slider: ^4.2.1

  #SVG File#
  flutter_svg: ^2.0.17
  google_fonts: ^6.1.0

  #------------/PACKAGES END--------#


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  #-------local assets------#
  assets:
    - assets/logos/
    - assets/icons/
    - assets/images/onboarding_images/
    - assets/images/verification_images/
    - assets/images/allimages/
    - assets/images/svgimages/



  #-------------LOCAL FONTS---------
  fonts:
    - family: Poppins
      fonts:
        - asset : assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800



