// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArzydZ7tIEo-9mM7WDWByR_1dm7w3wJu0',
    appId: '1:762361306872:android:114ad85163c56d5023250d',
    messagingSenderId: '762361306872',
    projectId: 'wastenot-cdfc8',
    storageBucket: 'wastenot-cdfc8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYYyL5JiC9X_xNDbPcuS77F6LXTJ2ZLZk',
    appId: '1:762361306872:ios:9f4a06babec87d8e23250d',
    messagingSenderId: '762361306872',
    projectId: 'wastenot-cdfc8',
    storageBucket: 'wastenot-cdfc8.firebasestorage.app',
    androidClientId: '762361306872-cbd1orbk0pkg02d8peo06te0tupmak1a.apps.googleusercontent.com',
    iosClientId: '762361306872-gfvmuo22qrm2cn6m8co4ed8mert5k467.apps.googleusercontent.com',
    iosBundleId: 'com.example.authentication',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4RWpYMCrrkdsat_G9Qbu004VTZkfw0Po',
    appId: '1:762361306872:web:47f0a2d84728a2a623250d',
    messagingSenderId: '762361306872',
    projectId: 'wastenot-cdfc8',
    authDomain: 'wastenot-cdfc8.firebaseapp.com',
    storageBucket: 'wastenot-cdfc8.firebasestorage.app',
  );

}